// backup-app/src/components/StatusBadge.vue
<template>
  <span
    :class="[
      'px-3 py-1 rounded-full text-xs font-medium',
      statusClasses[status] || statusClasses.idle,
    ]"
  >
    {{ statusLabels[status] || status }}
  </span>
</template>

<script setup lang="ts">
import type { BackupStatus } from '@/types'

interface Props {
  status: BackupStatus
}

defineProps<Props>()

const statusClasses: Record<BackupStatus, string> = {
  idle: 'bg-gray-600 text-gray-200',
  loading: 'bg-blue-600 text-white',
  scanning: 'bg-yellow-600 text-white',
  downloading: 'bg-green-600 text-white',
  saving: 'bg-purple-600 text-white',
  completed: 'bg-green-700 text-white',
  error: 'bg-red-600 text-white',
}

const statusLabels: Record<BackupStatus, string> = {
  idle: 'Ожидание',
  loading: 'Загрузка',
  scanning: 'Сканирование',
  downloading: 'Скачивание',
  saving: 'Сохранение',
  completed: 'Завершено',
  error: 'Ошибка',
}
</script>

// backup-app/src/components/StatusBadge.tsx
import type { BackupStatus } from '../types';

interface StatusBadgeProps {
  status: BackupStatus;
}

const statusConfig: Record<BackupStatus, { label: string; bgColor: string; dotColor: string; textColor: string }> = {
  idle: { label: 'Ожидание', bgColor: 'bg-gray-500', dotColor: 'bg-gray-500', textColor: 'text-gray-300' },
  loading: { label: 'Загрузка', bgColor: 'bg-blue-500', dotColor: 'bg-blue-500', textColor: 'text-blue-300' },
  scanning: { label: 'Сканирование', bgColor: 'bg-blue-500', dotColor: 'bg-blue-500', textColor: 'text-blue-300' },
  downloading: { label: 'Скачивание', bgColor: 'bg-green-500', dotColor: 'bg-green-500', textColor: 'text-green-300' },
  saving: { label: 'Сохранение', bgColor: 'bg-purple-500', dotColor: 'bg-purple-500', textColor: 'text-purple-300' },
  completed: { label: 'Завершено', bgColor: 'bg-green-600', dotColor: 'bg-green-600', textColor: 'text-green-300' },
  error: { label: 'Ошибка', bgColor: 'bg-red-500', dotColor: 'bg-red-500', textColor: 'text-red-300' },
};

export function StatusBadge({ status }: StatusBadgeProps) {
  const config = statusConfig[status];
  
  return (
    <div className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${config.bgColor} bg-opacity-20 ${config.textColor}`}>
      <div className={`w-2 h-2 rounded-full ${config.dotColor} mr-2`} />
      {config.label}
    </div>
  );
}
